language: node_js
node_js:
- '0.11'
- '0.10'
- '0.8'
- '0.6'
deploy:
  provider: heroku
  app: copibay-assembled
  api_key:
    secure: "DtZ/cyevk8eQqUHgK48uDYn3oF5fZnv62Ia0XWEUJJ1iowUA3fl4LIahVZdkH5yTHMMXAlwZivMrplfN+gkDzcz2dyOwmxDOXlzCRnYPYslK10GZ8AgmjRYKWnSUQVovihk4rRdDo3TBccVWPWda9Der1R51ZO4uSPca5aibDzk="
  strategy: git
before_deploy:
- git fetch --unshallow
