language: node_js
node_js:
- '0.11'
- '0.10'
- '0.8'
- '0.6'
deploy:
  provider: heroku
  app: copibay-assembled
  api_key:
    secure: "jfLjkW/tXS+NPKnW9ww6PFzuR6DWykn+1hTicvJcJ7/iR0MTTJgtTa6ttoz1notv82Y2Df0xRWLjQ0GDrj9NyIjoFbHX6OhOHLP1iT+B/6jchtYDoENYHUre9nLtab3S1gdzwZYeYVUkLEmsEsq5o8bm8J0pTTSmEHTHOEHT4O4="
  strategy: git
before_deploy:
- git fetch --unshallow
