language: node_js
node_js:
- '0.11'
- '0.10'
- '0.8'
- '0.6'
deploy:
  provider: heroku
  app: copibay-assembled
  api_key:
    secure: "V6DQt+KHhqtQlhUcAMKCzAYTLusPqkS+EsTlp+5u8EU0HOYYojXbolprGqs/SjXwPFcf/acnGPwwsibaLcFB2TEzr6qOCtPjEmaEQJsvIbm2/SEFX5xqAi+mlAU6hBjkZt3BCAOHcyWOAUQX7pQFTAUl8oERo9wkkOhGJBp/kuA="
  strategy: git
before_deploy:
- git fetch --unshallow
