language: node_js
node_js:
- '0.11'
- '0.10'
- '0.8'
- '0.6'
deploy:
  provider: heroku
  app: copibay-assembled
  api_key:
    secure: "anVEGNzWHfXyhUtqZ3KMPt4zZP+ZY+EA6cBKUtiVQvNEfLpOl5f495fpzvmH5/DvcfRMhtMW9+emXfRhy/RE2xGesXf5mKgOTjOnFaah2xAfw6qbdSStSNKhO/ZVOFh2bOHvcSV06TKXkUSiniO/TYpdprt6PbYl6/JPD7B1UDM="
  strategy: git
before_deploy:
- git fetch --unshallow
